# Generated by Django 5.1.1 on 2026-06-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short line shown on the collection card.', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('image_url', models.URLField(blank=True, help_text='Used only if no image is uploaded.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower shows first.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=60)),
                ('region', models.CharField(choices=[('west', 'West Malaysia'), ('east', 'East Malaysia (Sabah & Sarawak)')], default='west', max_length=4)),
                ('payment_method', models.CharField(choices=[('fpx', 'FPX Online Banking'), ('grabpay', 'GrabPay'), ('card', 'Credit / Debit Card')], default='fpx', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in MYR.', max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional 'was' price to show a discount.", max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
                ('sizes', models.CharField(default='XS,S,M,L', help_text='Comma separated, e.g. XS,S,M,L', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Main image (if not uploaded).')),
                ('hover_image_url', models.URLField(blank=True, help_text='Second image shown on hover.')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.product')),
            ],
        ),
    ]
