# Generated by Django 5.1.1 on 2026-06-19 02:33

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default=shop.models.generate_order_token, editable=False, max_length=32, unique=True),
        ),
    ]
