# Generated by Django 4.2.16 on 2026-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Customers type this at the cart, e.g. CNY10.', max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('percent', 'Percent off (%)'), ('fixed', 'Amount off (RM)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (e.g. 10) or RM amount (e.g. 30).', max_digits=6)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Minimum bag subtotal (RM) to use this code.', max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, help_text='Last valid day. Empty = no expiry.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Pieces available. 0 shows Sold Out.'),
        ),
    ]
