# Generated by Django 4.2.16 on 2026-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_coupon_order_coupon_code_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
