# Generated by Django 4.2.16 on 2026-07-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_subscriber_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('fpx', 'FPX Online Banking'), ('grabpay', 'GrabPay'), ('card', 'Credit / Debit Card'), ('transfer', 'Bank Transfer (WhatsApp)')], default='fpx', max_length=10),
        ),
    ]
