"""
Django settings for meiyi project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production set the SECRET_KEY environment variable on your host.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-l)q#=8q@=m459o$+#g#t_d*gmmw1$5zdru3wz056o@%(&sv+5s',
)

# SECURITY WARNING: don't run with debug turned on in production!
# On your host set DEBUG=false to turn this off.
DEBUG = os.environ.get('DEBUG', 'true').lower() == 'true'

# Hosts allowed to serve the site. Add your live domain via env on the host,
# e.g. ALLOWED_HOSTS="meiyi.onrender.com"
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')
]

# Admin login path. Bots try /admin/ on every Django site, so on your live
# host you can move it, e.g. ADMIN_URL="manage-meiyi-x7k2/". Keep it secret.
ADMIN_URL = (os.environ.get('ADMIN_URL') or 'admin/').strip('/') + '/'

# Production security — active only when DEBUG is off (i.e. on your live host).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'true').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30   # 30 days; raise once stable

# Safe browser defaults for both local and live environments. These prevent
# the shop/admin from being framed, reduce unnecessary referrer data, and
# stop browsers from guessing a file's content type.
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'shop',   # before contrib.admin so shop/templates/admin/ overrides win
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meiyi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_summary',
            ],
        },
    },
]

WSGI_APPLICATION = 'meiyi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# On a host with Postgres (e.g. Render), set DATABASE_URL and it takes over.
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'        # collectstatic target (for deploy)
# shop/static/ is discovered automatically because the shop app is installed.

# WhiteNoise: compress + cache static files when DEBUG is off (deploy)
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Render's local disk is temporary. On the live site, setting CLOUDINARY_URL
# sends every new ImageField upload to Cloudinary instead. Local development
# keeps using the media/ folder, so no account or secret is needed locally.
if os.environ.get('CLOUDINARY_URL'):
    STORAGES['default'] = {'BACKEND': 'shop.storages.CloudinaryMediaStorage'}

# Media files (product photos uploaded via the admin panel)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Customer accounts (optional — guests can still shop and check out).
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/account/'
LOGOUT_REDIRECT_URL = '/'

# --- Shop settings ---
FREE_SHIPPING_THRESHOLD = 350      # MYR
SHIPPING_WEST = 10                 # MYR, West Malaysia
SHIPPING_EAST = 18                 # MYR, East Malaysia (Sabah & Sarawak)

# WhatsApp chat button. PLACEHOLDER — replace with your real number
# (country code + number, no + or spaces), e.g. '60123456789'.
WHATSAPP_NUMBER = os.environ.get('WHATSAPP_NUMBER', '60123456789')

# --- Payments ---
# Live checkout stays on DuitNow transfer until online payments are enabled.
PAYMENT_MODE = os.environ.get(
    'PAYMENT_MODE', 'demo' if DEBUG else 'duitnow').lower()
DUITNOW_ID = os.environ.get('DUITNOW_ID', '')

# Optional toyyibPay settings for a future online-payment switch.
# Leave the keys empty = demo mode (orders marked paid instantly, no money moves).
# 1) Register at https://toyyibpay.com (sandbox: https://dev.toyyibpay.com)
# 2) Create a Category, then set these environment variables:
#    TOYYIBPAY_SECRET_KEY, TOYYIBPAY_CATEGORY_CODE
# 3) For live payments also set TOYYIBPAY_BASE_URL=https://toyyibpay.com
TOYYIBPAY_SECRET_KEY = os.environ.get('TOYYIBPAY_SECRET_KEY', '')
TOYYIBPAY_CATEGORY_CODE = os.environ.get('TOYYIBPAY_CATEGORY_CODE', '')
TOYYIBPAY_BASE_URL = os.environ.get('TOYYIBPAY_BASE_URL', 'https://dev.toyyibpay.com')

# Public address of the site — used for payment return/callback links.
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# Bank-transfer mode: no gateway keys + live site (DEBUG=false) = orders stay
# Pending, the customer gets WhatsApp payment instructions, and you press
# "Mark as PAID" in the admin once the transfer arrives. On by default on a
# live site without keys; set MANUAL_PAYMENT=true to try it in development.
MANUAL_PAYMENT = os.environ.get(
    'MANUAL_PAYMENT', '' if DEBUG else 'true').lower() == 'true'

# --- Email (order confirmations) ---
# Default: emails print to the terminal (development). For real email set e.g.:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.gmail.com  EMAIL_HOST_USER=you@gmail.com
#   EMAIL_HOST_PASSWORD=<app password>  DEFAULT_FROM_EMAIL="Méiyì <you@gmail.com>"
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL',
                                    'Méiyì Atelier <no-reply@meiyi.local>')
